Repository cjdrkd7668/SsangYongBangProject, pull requests merged in 2021-02, with the labels that each got.

#1 필요한 xml과 jar 생성
  SsangYongBang/WebContent/WEB-INF/lib/cos.jar
  SsangYongBang/WebContent/WEB-INF/lib/jstl-1.2.jar
  SsangYongBang/WebContent/WEB-INF/lib/ojdbc6.jar
  SsangYongBang/WebContent/WEB-INF/web.xml
Labels: good first issue

#3 협업 테스트
  SsangYongBang/WebContent/WEB-INF/views/index.jsp
Labels: wontfix

#66 Build Path 수정
  SsangYongBang/.classpath
  SsangYongBang/WebContent/WEB-INF/views/notice/boardList.jsp
  SsangYongBang/WebContent/WEB-INF/views/notice/header.jsp
  SsangYongBang/WebContent/images/logo.png
  SsangYongBang/src/com/test/sist/notice/BoardList.java
  SsangYongBang/src/com/test/sist/notice/Header.java
Labels: error fixed

#91 헤더 드랍다운 추가 & 푸터 수정
  SsangYongBang/WebContent/WEB-INF/views/inc/footer.jsp
  SsangYongBang/WebContent/WEB-INF/views/inc/header.jsp
  SsangYongBang/WebContent/css/main.css
Labels: enhancement, error fixed

#94 뉴스 게시판과 관리자 알림 센터
  SsangYongBang/WebContent/WEB-INF/views/admin/index.jsp
  SsangYongBang/WebContent/WEB-INF/views/inc/header.jsp
  SsangYongBang/WebContent/WEB-INF/views/news/boardList.jsp
  SsangYongBang/WebContent/css/admin.css
  SsangYongBang/WebContent/images/right_icon.png
  SsangYongBang/src/com/test/sist/inc/Footer.java
  SsangYongBang/src/com/test/sist/inc/Header.java
  SsangYongBang/src/com/test/sist/news/BoardList.java
Labels: enhancement

#99 헤더 마이페이지 드랍다운 추가
  SsangYongBang/WebContent/WEB-INF/views/inc/header.jsp
  SsangYongBang/WebContent/css/main.css
Labels: enhancement

#114 특정 매물 조회 화면 구현
  SsangYongBang/WebContent/WEB-INF/views/admin/house/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/admin/house/view.jsp
  SsangYongBang/WebContent/WEB-INF/views/admin/index.jsp
  SsangYongBang/WebContent/css/admin.css
  SsangYongBang/src/com/test/sist/admin/house/View.java
Labels: enhancement

#115 ㎠를 ㎡로 오타 수정
  SsangYongBang/WebContent/WEB-INF/views/house/post.jsp
Labels: fix typo

#117 메인 index 수정
  SsangYongBang/WebContent/WEB-INF/views/index.jsp
Labels: enhancement

#118 방찾기 상세페이지 수정
  SsangYongBang/WebContent/WEB-INF/views/house/detail.jsp
  SsangYongBang/WebContent/css/housedetail.css
Labels: enhancement

#122 방찾기 상세페이지 height 수정
  SsangYongBang/WebContent/WEB-INF/views/house/detail.jsp
  SsangYongBang/WebContent/css/housedetail.css
Labels: enhancement

#125 관리자 희망입주조건 관리 목록 구현
  SsangYongBang/WebContent/WEB-INF/views/admin/hope/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/admin/house/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/admin/room/boardlist.jsp
  SsangYongBang/WebContent/css/admin.css
  SsangYongBang/WebContent/css/board.css
Labels: enhancement

#126 희망 입주 정보에서 희망 입주하기로 수정
  SsangYongBang/WebContent/WEB-INF/views/hope/list.jsp
  SsangYongBang/WebContent/WEB-INF/views/hope/post.jsp
  SsangYongBang/WebContent/WEB-INF/views/inc/header.jsp
  SsangYongBang/WebContent/css/hopepost.css
  SsangYongBang/src/com/test/sist/hope/Post.java
Labels: enhancement

#128 희망입주하기, 방내놓기에 목록보기 버튼 추가
  SsangYongBang/WebContent/WEB-INF/views/hope/post.jsp
  SsangYongBang/WebContent/WEB-INF/views/house/post.jsp
  SsangYongBang/WebContent/WEB-INF/views/inc/header.jsp
Labels: enhancement

#129 희망 입주 정보 글 조회하는 화면 작성
  SsangYongBang/WebContent/WEB-INF/views/hope/list.jsp
  SsangYongBang/WebContent/WEB-INF/views/hope/post.jsp
  SsangYongBang/WebContent/WEB-INF/views/hope/view.jsp
  SsangYongBang/WebContent/WEB-INF/views/house/list.jsp
  SsangYongBang/WebContent/WEB-INF/views/house/post.jsp
  SsangYongBang/src/com/test/sist/hope/View.java
Labels: client page

#133 자유게시판 글쓰기 작성
  SsangYongBang/WebContent/WEB-INF/views/board/freelist.jsp
  SsangYongBang/WebContent/WEB-INF/views/board/freepost.jsp
  SsangYongBang/WebContent/WEB-INF/views/hope/post.jsp
  SsangYongBang/WebContent/WEB-INF/views/hope/view.jsp
  SsangYongBang/WebContent/WEB-INF/views/house/post.jsp
  SsangYongBang/WebContent/WEB-INF/views/member/login.jsp
  SsangYongBang/WebContent/css/freepost.css
  SsangYongBang/WebContent/css/memberlogin.css
  SsangYongBang/src/com/test/sist/board/FreePost.java
Labels: client page

#135 자유게시판 상세페이지 작성
  SsangYongBang/WebContent/WEB-INF/views/board/freedetail.jsp
  SsangYongBang/WebContent/WEB-INF/views/board/freelist.jsp
  SsangYongBang/WebContent/css/freedetail.css
  SsangYongBang/src/com/test/sist/board/FreeDetail.java
Labels: client page

#143 관리자 업체 승인 페이지 구현
  SsangYongBang/WebContent/WEB-INF/views/approval/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/inc/admin_left.jsp
  SsangYongBang/WebContent/WEB-INF/views/inc/footer.jsp
  SsangYongBang/WebContent/css/admin.css
  SsangYongBang/src/com/test/sist/approval/BoardList.java
Labels: enhancement

#144 관리자 허위 매물 삭제 게시판 구현
  SsangYongBang/WebContent/WEB-INF/views/admin/hope/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/admin/house/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/admin/room/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/falsepost/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/inc/admin_left.jsp
  SsangYongBang/WebContent/css/admin.css
  SsangYongBang/WebContent/css/board.css
  SsangYongBang/src/com/test/sist/falsepost/BoardList.java
Labels: enhancement

#158 관리자 후기 삭제 요청 게시판 클라이언트 구현
  SsangYongBang/WebContent/WEB-INF/views/admin/review/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/approval/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/falsepost/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/inc/admin_left.jsp
  SsangYongBang/WebContent/css/admin.css
  SsangYongBang/src/com/test/sist/admin/review/BoardList.java
Labels: enhancement

#160 로그인 버튼 클라이언트 페이지
  SsangYongBang/WebContent/WEB-INF/views/inc/header.jsp
  SsangYongBang/WebContent/WEB-INF/views/login/loginbuttons.jsp
  SsangYongBang/src/com/test/sist/loginselect/LoginButtons.java
Labels: enhancement

#164 관리자 광고중인 중개사 목록 조회 클라이언트 페이지 구현
  SsangYongBang/WebContent/WEB-INF/views/admin/ad/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/falsepost/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/inc/admin_left.jsp
  SsangYongBang/WebContent/css/admin.css
  SsangYongBang/src/com/test/sist/admin/ad/BoardList.java
Labels: enhancement

#170 관리자 로그인 기능 구현
  SsangYongBang/WebContent/WEB-INF/views/admin/auth.jsp
  SsangYongBang/WebContent/WEB-INF/views/admin/login.jsp
  SsangYongBang/WebContent/WEB-INF/views/login/loginbuttons.jsp
  SsangYongBang/src/com/test/sist/admin/AdminDAO.java
  SsangYongBang/src/com/test/sist/admin/AdminDTO.java
  SsangYongBang/src/com/test/sist/admin/Auth.java
  SsangYongBang/src/com/test/sist/admin/Login.java
Labels: enhancement

#171 codestudy JRE 라이브러리 path 수정
  codestudy/.classpath
  codestudy/build/classes/com/test/codestudy/BarDTO.class
  codestudy/build/classes/com/test/codestudy/DBUtil.class
  codestudy/build/classes/com/test/codestudy/Index.class
  codestudy/build/classes/com/test/codestudy/PiDTO.class
  codestudy/build/classes/com/test/codestudy/board/BoardDAO.class
  codestudy/build/classes/com/test/codestudy/board/BoardDTO.class
  codestudy/build/classes/com/test/codestudy/board/CommentDTO.class
  codestudy/build/classes/com/test/codestudy/board/CommentOk.class
  codestudy/build/classes/com/test/codestudy/board/Delete.class
  codestudy/build/classes/com/test/codestudy/board/DeleteCommentOk.class
  codestudy/build/classes/com/test/codestudy/board/DeleteOk.class
  codestudy/build/classes/com/test/codestudy/board/Download.class
  codestudy/build/classes/com/test/codestudy/board/Dummy.class
  codestudy/build/classes/com/test/codestudy/board/Edit.class
  codestudy/build/classes/com/test/codestudy/board/EditOk.class
  codestudy/build/classes/com/test/codestudy/board/List.class
  codestudy/build/classes/com/test/codestudy/board/View.class
  codestudy/build/classes/com/test/codestudy/board/Write.class
  codestudy/build/classes/com/test/codestudy/board/WriteOk.class
  codestudy/build/classes/com/test/codestudy/example/Index.class
  codestudy/build/classes/com/test/codestudy/history/Index.class
  codestudy/build/classes/com/test/codestudy/inc/Auth.class
  codestudy/build/classes/com/test/codestudy/inc/Chat.class
  codestudy/build/classes/com/test/codestudy/inc/Header.class
  codestudy/build/classes/com/test/codestudy/inc/Menu.class
  codestudy/build/classes/com/test/codestudy/member/Auth.class
  codestudy/build/classes/com/test/codestudy/member/Login.class
  codestudy/build/classes/com/test/codestudy/member/Logout.class
  codestudy/build/classes/com/test/codestudy/member/MemberDAO.class
  codestudy/build/classes/com/test/codestudy/member/MemberDTO.class
  codestudy/build/classes/com/test/codestudy/member/Message.class
  codestudy/build/classes/com/test/codestudy/member/MessageDTO.class
  codestudy/build/classes/com/test/codestudy/member/Register.class
  codestudy/build/classes/com/test/codestudy/member/RegisterOk.class
  codestudy/build/classes/com/test/codestudy/member/Send.class
  codestudy/build/classes/com/test/codestudy/member/SendOk.class
  codestudy/build/classes/com/test/codestudy/member/View.class
  codestudy/build/classes/com/test/codestudy/plan/Index.class
  codestudy/build/classes/com/test/codestudy/review/List.class
  codestudy/build/classes/com/test/codestudy/review/Write.class
Labels: error fixed

#173 자유게시판 최신글, 댓글수 표시
  SsangYongBang/WebContent/WEB-INF/views/board/freelist.jsp
  SsangYongBang/WebContent/WEB-INF/views/inc/header.jsp
Labels: enhancement

#174 최신 댓글 표시
  SsangYongBang/WebContent/WEB-INF/views/board/freedetail.jsp
  SsangYongBang/src/com/test/sist/board/FreeCommentDTO.java
  SsangYongBang/src/com/test/sist/board/FreeDAO.java
  SsangYongBang/src/com/test/sist/board/FreeDeleteComment.java
  SsangYongBang/src/com/test/sist/board/header.jsp
Labels: enhancement

#179 관리자 희망입주조건 관리 게시판 JSP 구현
  SsangYongBang/WebContent/WEB-INF/views/admin/hope/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/inc/admin_left.jsp
  SsangYongBang/WebContent/css/admin.css
  SsangYongBang/src/com/test/sist/admin/hope/AdminHopeDAO.java
  SsangYongBang/src/com/test/sist/admin/hope/AdminHopeDTO.java
  SsangYongBang/src/com/test/sist/admin/hope/BoardList.java
  SsangYongBang/src/com/test/sist/inc/Pagination.java
  codestudy/WebContent/WEB-INF/views/board/list.jsp
Labels: enhancement

#184 문의게시판 목록 구현
  SsangYongBang/src/com/test/sist/board/InquiryDAO.java
  SsangYongBang/src/com/test/sist/board/InquiryList.java
Labels: enhancement

#186 문의게시판 글작성 구현
  SsangYongBang/WebContent/WEB-INF/views/board/inquirypost.jsp
  SsangYongBang/WebContent/WEB-INF/views/inc/header.jsp
  SsangYongBang/src/com/test/sist/board/InquiryDAO.java
  SsangYongBang/src/com/test/sist/board/InquiryDTO.java
  SsangYongBang/src/com/test/sist/board/InquiryList.java
  SsangYongBang/src/com/test/sist/board/InquiryPostOk.java
Labels: enhancement

#192 관리자 후기 삭제 요청 JSP 구현
  SsangYongBang/.classpath
  SsangYongBang/.settings/org.eclipse.wst.common.project.facet.core.xml
  SsangYongBang/WebContent/WEB-INF/views/admin/review/boardlist.jsp
  SsangYongBang/src/com/test/sist/admin/review/AdminReviewDAO.java
  SsangYongBang/src/com/test/sist/admin/review/DeleteOk.java
  SsangYongBang/src/com/test/sist/admin/review/ReviewDeleteOk.java
  codestudy/src/com/test/codestudy/board/DeleteOk.java
Labels: enhancement

#197 중개사 프로필 수정하기
  SsangYongBang/WebContent/WEB-INF/views/broker/brokerMain.jsp
  SsangYongBang/src/com/test/sist/admin/room/View.java
  SsangYongBang/src/com/test/sist/broker/BrokerDAO.java
  SsangYongBang/src/com/test/sist/broker/EditOk.java
  codestudy/.classpath
  codestudy/.settings/org.eclipse.wst.common.project.facet.core.xml
  codestudy/build/classes/com/test/codestudy/Index.class
  codestudy/build/classes/com/test/codestudy/board/CommentOk.class
  codestudy/build/classes/com/test/codestudy/board/Delete.class
  codestudy/build/classes/com/test/codestudy/board/DeleteCommentOk.class
  codestudy/build/classes/com/test/codestudy/board/DeleteOk.class
  codestudy/build/classes/com/test/codestudy/board/Download.class
  codestudy/build/classes/com/test/codestudy/board/Edit.class
  codestudy/build/classes/com/test/codestudy/board/EditOk.class
  codestudy/build/classes/com/test/codestudy/board/List.class
  codestudy/build/classes/com/test/codestudy/board/View.class
  codestudy/build/classes/com/test/codestudy/board/Write.class
  codestudy/build/classes/com/test/codestudy/board/WriteOk.class
  codestudy/build/classes/com/test/codestudy/example/Index.class
  codestudy/build/classes/com/test/codestudy/history/Index.class
  codestudy/build/classes/com/test/codestudy/inc/Auth.class
  codestudy/build/classes/com/test/codestudy/inc/Chat.class
  codestudy/build/classes/com/test/codestudy/inc/Header.class
  codestudy/build/classes/com/test/codestudy/inc/Menu.class
  codestudy/build/classes/com/test/codestudy/member/Auth.class
  codestudy/build/classes/com/test/codestudy/member/Login.class
  codestudy/build/classes/com/test/codestudy/member/Logout.class
  codestudy/build/classes/com/test/codestudy/member/Message.class
  codestudy/build/classes/com/test/codestudy/member/Register.class
  codestudy/build/classes/com/test/codestudy/member/RegisterOk.class
  codestudy/build/classes/com/test/codestudy/member/Send.class
  codestudy/build/classes/com/test/codestudy/member/SendOk.class
  codestudy/build/classes/com/test/codestudy/member/View.class
  codestudy/build/classes/com/test/codestudy/plan/Index.class
  codestudy/build/classes/com/test/codestudy/review/List.class
  codestudy/build/classes/com/test/codestudy/review/Write.class
Labels: enhancement

#200 공지사항 삭제, 글쓰기 구현
  SsangYongBang/WebContent/WEB-INF/views/notice/delete.jsp
  SsangYongBang/WebContent/WEB-INF/views/notice/post.jsp
  SsangYongBang/src/com/test/sist/notice/Delete.java
  SsangYongBang/src/com/test/sist/notice/DeleteOk.java
  SsangYongBang/src/com/test/sist/notice/NoticeDAO.java
  SsangYongBang/src/com/test/sist/notice/Post.java
  SsangYongBang/src/com/test/sist/notice/PostOk.java
Labels: enhancement

#212 자유게시판(댓글 수정) 구현
  SsangYongBang/WebContent/WEB-INF/views/board/freedelete.jsp
  SsangYongBang/WebContent/WEB-INF/views/free/post.jsp
  SsangYongBang/src/com/test/sist/board/FreeCommentOk.java
  SsangYongBang/src/com/test/sist/free/CommentOk.java
  SsangYongBang/src/com/test/sist/free/DeleteCommentOk.java
  SsangYongBang/src/com/test/sist/free/dao/FreeCommentDAO.java
  SsangYongBang/src/com/test/sist/inquiry/List.java
Labels: enhancement

#214 방 내놓기 기능 구현중 / 도로명 주소 API / 방 내놓기 및 희망입주하기 접근 검사
  SsangYongBang/WebContent/WEB-INF/views/admin/room/view.jsp
  SsangYongBang/WebContent/WEB-INF/views/house/Sample.jsp
  SsangYongBang/WebContent/WEB-INF/views/house/jusoPopup.jsp
  SsangYongBang/WebContent/WEB-INF/views/house/post.jsp
  SsangYongBang/WebContent/WEB-INF/views/member/login.jsp
  SsangYongBang/WebContent/css/housepost.css
  SsangYongBang/src/com/test/sist/hope/Post.java
  SsangYongBang/src/com/test/sist/house/JusoPopup.java
  SsangYongBang/src/com/test/sist/house/Post.java
  SsangYongBang/src/com/test/sist/house/PostOk.java
  SsangYongBang/src/com/test/sist/house/RoomImgDTO.java
  SsangYongBang/src/com/test/sist/room/RoomDTO.java
  codestudy/.classpath
  codestudy/build/classes/com/test/codestudy/Index.class
  codestudy/build/classes/com/test/codestudy/board/CommentOk.class
  codestudy/build/classes/com/test/codestudy/board/Delete.class
  codestudy/build/classes/com/test/codestudy/board/DeleteCommentOk.class
  codestudy/build/classes/com/test/codestudy/board/DeleteOk.class
  codestudy/build/classes/com/test/codestudy/board/Download.class
  codestudy/build/classes/com/test/codestudy/board/Edit.class
  codestudy/build/classes/com/test/codestudy/board/EditOk.class
  codestudy/build/classes/com/test/codestudy/board/List.class
  codestudy/build/classes/com/test/codestudy/board/View.class
  codestudy/build/classes/com/test/codestudy/board/Write.class
  codestudy/build/classes/com/test/codestudy/board/WriteOk.class
  codestudy/build/classes/com/test/codestudy/example/Index.class
  codestudy/build/classes/com/test/codestudy/history/Index.class
  codestudy/build/classes/com/test/codestudy/inc/Auth.class
  codestudy/build/classes/com/test/codestudy/inc/Chat.class
  codestudy/build/classes/com/test/codestudy/inc/Header.class
  codestudy/build/classes/com/test/codestudy/inc/Menu.class
  codestudy/build/classes/com/test/codestudy/member/Auth.class
  codestudy/build/classes/com/test/codestudy/member/Login.class
  codestudy/build/classes/com/test/codestudy/member/Logout.class
  codestudy/build/classes/com/test/codestudy/member/Message.class
  codestudy/build/classes/com/test/codestudy/member/Register.class
  codestudy/build/classes/com/test/codestudy/member/RegisterOk.class
  codestudy/build/classes/com/test/codestudy/member/Send.class
  codestudy/build/classes/com/test/codestudy/member/SendOk.class
  codestudy/build/classes/com/test/codestudy/member/View.class
  codestudy/build/classes/com/test/codestudy/plan/Index.class
  codestudy/build/classes/com/test/codestudy/review/List.class
  codestudy/build/classes/com/test/codestudy/review/Write.class
Labels: enhancement, on progress

#215 문의게시판 CSS 수정 + 구현
  SsangYongBang/WebContent/WEB-INF/views/board/inquirydelete.jsp
  SsangYongBang/WebContent/WEB-INF/views/board/inquiryedit.jsp
  SsangYongBang/WebContent/WEB-INF/views/board/inquirypost.jsp
  SsangYongBang/WebContent/WEB-INF/views/free/detail.jsp
  SsangYongBang/WebContent/WEB-INF/views/free/list.jsp
  SsangYongBang/WebContent/WEB-INF/views/inc/header.jsp
  SsangYongBang/WebContent/WEB-INF/views/inquiry/delete.jsp
  SsangYongBang/WebContent/WEB-INF/views/inquiry/detail.jsp
  SsangYongBang/WebContent/WEB-INF/views/inquiry/edit.jsp
  SsangYongBang/WebContent/WEB-INF/views/inquiry/list.jsp
  SsangYongBang/WebContent/WEB-INF/views/inquiry/post.jsp
  SsangYongBang/WebContent/css/globaldetail.css
  SsangYongBang/WebContent/css/globallist.css
  SsangYongBang/src/com/test/sist/board/FreeCommentDAO.java
  SsangYongBang/src/com/test/sist/board/FreeCommentDTO.java
  SsangYongBang/src/com/test/sist/board/FreeDAO.java
  SsangYongBang/src/com/test/sist/board/FreeDTO.java
  SsangYongBang/src/com/test/sist/board/FreeEditComment.java
  SsangYongBang/src/com/test/sist/board/InquiryList.java
  SsangYongBang/src/com/test/sist/board/InquiryPost.java
  SsangYongBang/src/com/test/sist/inquiry/Delete.java
  SsangYongBang/src/com/test/sist/inquiry/DeleteOk.java
  SsangYongBang/src/com/test/sist/inquiry/Detail.java
  SsangYongBang/src/com/test/sist/inquiry/Edit.java
  SsangYongBang/src/com/test/sist/inquiry/EditOk.java
  SsangYongBang/src/com/test/sist/inquiry/List.java
  SsangYongBang/src/com/test/sist/inquiry/Post.java
  SsangYongBang/src/com/test/sist/inquiry/PostOk.java
  SsangYongBang/src/com/test/sist/inquiry/dao/InquiryCommentDAO.java
  SsangYongBang/src/com/test/sist/inquiry/dao/InquiryDAO.java
  SsangYongBang/src/com/test/sist/inquiry/dto/InquiryCommentDTO.java
  SsangYongBang/src/com/test/sist/inquiry/dto/InquiryDTO.java
Labels: enhancement

#219 자유게시판, 문의게시판 구현 끝
  SsangYongBang/WebContent/WEB-INF/views/free/detail.jsp
  SsangYongBang/WebContent/WEB-INF/views/free/list.jsp
  SsangYongBang/WebContent/WEB-INF/views/house/search.jsp
  SsangYongBang/WebContent/WEB-INF/views/inquiry/detail.jsp
  SsangYongBang/WebContent/images/bg.jpg
  SsangYongBang/WebContent/images/notice001.png
  SsangYongBang/WebContent/images/notice002.png
  SsangYongBang/WebContent/images/notice003.png
  SsangYongBang/src/com/test/sist/free/EditCommentOk.java
  SsangYongBang/src/com/test/sist/free/dao/FreeCommentDAO.java
  SsangYongBang/src/com/test/sist/inquiry/EditCommentOk.java
  SsangYongBang/src/com/test/sist/inquiry/dao/InquiryCommentDAO.java
  SsangYongBang/src/com/test/sist/member/ChangeInfo.java
  SsangYongBang/src/com/test/sist/member/Login.java
  SsangYongBang/src/com/test/sist/member/LoginOk.java
  SsangYongBang/src/com/test/sist/member/Logout.java
  SsangYongBang/src/com/test/sist/member/MemberDTO.java
  SsangYongBang/src/com/test/sist/member/MyInfo.java
Labels: enhancement

#222 특정 방 조회 페이지 방 이미지 슬라이드 구현
  SsangYongBang/WebContent/WEB-INF/views/admin/room/view.jsp
  SsangYongBang/WebContent/WEB-INF/views/house/view.jsp
  SsangYongBang/WebContent/images/room0001.jpg
  SsangYongBang/WebContent/images/room0002.jpg
  SsangYongBang/WebContent/images/room0003.jpg
  SsangYongBang/WebContent/images/room0004.jpg
  SsangYongBang/WebContent/images/room0005.jpg
  SsangYongBang/WebContent/images/room0006.jpg
  SsangYongBang/WebContent/images/room0007.jpg
  SsangYongBang/WebContent/images/room0008.jpg
  SsangYongBang/WebContent/images/room0009.jpg
  SsangYongBang/WebContent/images/room0010.jpg
  SsangYongBang/src/com/test/sist/admin/room/View.java
  SsangYongBang/src/com/test/sist/house/View.java
  SsangYongBang/src/com/test/sist/room/RoomDAO.java
Labels: enhancement

#228 내정보관리 - 내가 쓴 글, 내가 쓴 댓글 구현
  SsangYongBang/.classpath
  SsangYongBang/.settings/org.eclipse.wst.common.component
  SsangYongBang/WebContent/WEB-INF/views/member/myinfo.jsp
  SsangYongBang/WebContent/css/mypage.css
  SsangYongBang/src/com/test/sist/member/MyCommentData.java
  SsangYongBang/src/com/test/sist/member/MyInfo.java
  SsangYongBang/src/com/test/sist/member/MyInfoDAO.java
  SsangYongBang/src/com/test/sist/member/MyInfoDTO.java
  SsangYongBang/src/com/test/sist/member/MyPostDAO.java
  SsangYongBang/src/com/test/sist/member/MyPostOk.java
Labels: enhancement

#238 공지사항 화면 수정
  SsangYongBang/WebContent/WEB-INF/views/free/list.jsp
  SsangYongBang/WebContent/WEB-INF/views/inquiry/list.jsp
  SsangYongBang/WebContent/WEB-INF/views/notice/detail.jsp
  SsangYongBang/WebContent/WEB-INF/views/notice/list.jsp
  SsangYongBang/WebContent/css/globallist.css
  SsangYongBang/src/com/test/sist/inquiry/List.java
  SsangYongBang/src/com/test/sist/member/MyCommentData.java
  SsangYongBang/src/com/test/sist/notice/NoticeDAO.java
  SsangYongBang/src/com/test/sist/room/RoomDTO.java
Labels: enhancement

#240 내가 쓴 댓글 ajax 넘어 가는 값 수정
  SsangYongBang/.classpath
  SsangYongBang/WebContent/WEB-INF/views/member/myinfo.jsp
  SsangYongBang/src/com/test/sist/free/EditOk.java
  SsangYongBang/src/com/test/sist/inquiry/EditOk.java
Labels: error fixed

#241 관리자 - 매물 관리 구현
  SsangYongBang/WebContent/WEB-INF/views/admin/house/boardlist.jsp
  SsangYongBang/WebContent/WEB-INF/views/admin/house/view.jsp
  SsangYongBang/src/com/test/sist/admin/house/BoardList.java
  SsangYongBang/src/com/test/sist/admin/house/View.java
  SsangYongBang/src/com/test/sist/admin/room/BoardList.java
  SsangYongBang/src/com/test/sist/house/dao/HouseDAO.java
Labels: enhancement

#242 관리자 - 매물 관리 삭제 구현
  SsangYongBang/WebContent/WEB-INF/views/admin/house/view.jsp
  SsangYongBang/WebContent/css/freedetail.css
  SsangYongBang/WebContent/css/housedetail.css
  SsangYongBang/src/com/test/sist/admin/house/DeleteOk.java
  SsangYongBang/src/com/test/sist/house/dao/HouseDAO.java
Labels: enhancement

#247 방 찾기 페이지 드디어 완성!!
  SsangYongBang/WebContent/WEB-INF/views/house/houseview.jsp
  SsangYongBang/WebContent/WEB-INF/views/house/search.jsp
  SsangYongBang/src/com/test/sist/house/HouseView.java
  SsangYongBang/src/com/test/sist/house/SearchJsonData.java
  SsangYongBang/src/com/test/sist/house/dao/HouseDAO.java
Labels: enhancement
